name: PR Action

on:
  push:
    branches: 'qa'

jobs:
  createpr:
    name: PR Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: pgalchemy/one-commit-pr-action
          token: ${{ secrets.GITHUB_PAT }}
          path: .github/actions/my-action
      - name: Run My Action
        uses: ./.github/actions/my-action