name: prBuild
on:
  push:
    branches:
      - stage
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          - name: Set output
            id: vars
            run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

          - name: Check output
            run: echo ${{ steps.vars.outputs.short_ref }}

     - name: Two
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ BRANCH_NAME} }}
          pr_title: "Pulling ${{steps.vars.outputs.short_ref } into master"
          pr_draft: true
