name: prBuild
on:
  push:
    branches:
      - stage
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: extract_branch

     - name: Two
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ BRANCH_NAME} }}
          pr_title: "Pulling ${{steps.extract_branch.outputs.branch}} into master"
          pr_draft: true
