name: prBuild
on:
  push:
    branches:
      - stage
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Pulling ${{ github.ref }} into master"
          pr_draft: true
