name: prBuild
on:
  push:
    branches:
      - stage
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: One
        - uses: actions/checkout@v1
        - run: npm ci
        - uses: nelonoel/branch-name@v1
        # Use branch name for whatever purpose
        - run: echo ${BRANCH_NAME}
          -
     - name: Two
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ BRANCH_NAME} }}
          pr_title: "Pulling ${{ github.event.pull_request.head.ref }} into master"
          pr_draft: true
