name: tfsec
on: [push]
jobs:
  tfsec:
    name: TF Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1.2
        with:
          tfsec_actions_working_dir: = ./infrastructure
          tfsec_actions_comment: false

    